# Generated by Django 4.0.6 on 2022-12-06 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentmodule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_date',
        ),
    ]
