# Generated by Django 4.0.6 on 2022-12-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmodule', '0003_reservation_comments_reservation_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
