# Generated by Django 4.0.6 on 2022-12-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentmodule', '0004_reservation_deleted_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='car',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
