# Generated by Django 4.0.6 on 2023-06-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmodule', '0006_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
